// Pure title/date logic — no React, no Mastra imports — because it is bundled by
// both Vite (Live Preview + Slack card) and Mastra's own server bundler (the
// agent's dynamic instructions need today's date). Relative, extensionless
// imports for the same reason: Mastra's bundler doesn't resolve the `@/` alias.
import {
  RELEASE_NOTES_DEFAULT_TIME_ZONE,
  RELEASE_NOTES_TITLE_PREFIX,
} from '../../constants/release-notes';
import { Platform } from '../../types/platform';
import { DRAFT_FIELD_BY_PLATFORM } from '../../types/release-notes-draft';
import type { ReleaseNotesDraft } from '../../types/release-notes-draft';

// en-CA is the one widely-supported locale that formats as YYYY-MM-DD, so dropping
// the separators is both shorter and less error-prone than reassembling
// formatToParts() by hand.
export const formatReleaseDate = (
  now: Date = new Date(),
  timeZone: string = RELEASE_NOTES_DEFAULT_TIME_ZONE,
): string =>
  new Intl.DateTimeFormat('en-CA', {
    timeZone,
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
  })
    .format(now)
    .replaceAll('-', '');

// The title is composed here rather than generated by the model: the default shape
// is then guaranteed by construction instead of depending on the model getting it
// right every turn. The model only supplies the two things it alone can know —
// which date the user asked for, and whether the user explicitly asked for a
// different title altogether.
export const buildReleaseTitle = (
  { releaseDate, titleOverride }: ReleaseNotesDraft,
  now?: Date,
): string =>
  titleOverride ??
  `${RELEASE_NOTES_TITLE_PREFIX}${releaseDate ?? formatReleaseDate(now)}`;

// The single source of truth for "the text of this draft" — the Live Preview, the
// Copy button, and the Slack confirmation card all read it, so they cannot show
// three different things.
export const composeDraftContent = (
  draft: ReleaseNotesDraft,
  platform: Platform,
  now?: Date,
): string => {
  const title = buildReleaseTitle(draft, now);
  const body = draft[DRAFT_FIELD_BY_PLATFORM[platform]];

  // Only GitHub renders Markdown; an `#` in the App Store / Google Play fields would
  // reach the store listing as a literal hash character.
  return platform === Platform.Github
    ? `# ${title}\n\n${body}`
    : `${title}\n\n${body}`;
};
